<a href="https://colab.research.google.com/github/MohmedFahmy/NumpyLib/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,2,3])
arr1

array([1, 2, 3])

In [ ]:
np.array([1,2,3,4,12],dtype=np.float32)

array([ 1.,  2.,  3.,  4., 12.], dtype=float32)

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#D array
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.random.random((5,5))

array([[0.58982786, 0.67991407, 0.68908212, 0.38498081, 0.88529773],
       [0.78614488, 0.63951988, 0.12902753, 0.57651034, 0.20220168],
       [0.44483712, 0.57345412, 0.67704134, 0.33933964, 0.17303092],
       [0.97664507, 0.47908265, 0.47719287, 0.89225684, 0.00961442],
       [0.57482236, 0.30275795, 0.3975728 , 0.57813403, 0.59144047]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[ 0.14593354,  1.17959334,  1.3855545 ],
       [-0.68204805, -0.87187137, -0.74514721],
       [ 0.38567611, -1.32490696, -1.10718591]])

In [ ]:
np.random.randint(0,10,(3,3))

array([[0, 0, 4],
       [6, 6, 0],
       [0, 6, 7]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#to storage place in memory
np.empty(3)

array([1., 1., 1.])

In [ ]:
rng=np.random.default_rng(seed=1741)
x1=rng.integers(10,size=6)
x1

array([3, 9, 3, 0, 5, 6])

In [ ]:
x2=rng.integers(10,size=(3,4))
x3=rng.integers(10,size=(3,4,5))

In [ ]:
x3.ndim #num od dimintions

3

In [ ]:
x3.shape

(3, 4, 5)

In [ ]:
x3.size

60

In [ ]:
x3.dtype

dtype('int64')

In [ ]:
x2

array([[9, 9, 8, 2],
       [5, 4, 5, 7],
       [9, 0, 1, 0]])

In [ ]:
x3

array([[[9, 3, 5, 2, 5],
        [4, 5, 0, 9, 4],
        [2, 8, 2, 7, 9],
        [2, 9, 3, 4, 8]],

       [[5, 2, 8, 3, 8],
        [2, 6, 9, 8, 5],
        [5, 6, 0, 7, 2],
        [5, 3, 0, 2, 4]],

       [[1, 8, 0, 2, 9],
        [4, 0, 7, 5, 4],
        [0, 0, 1, 7, 0],
        [8, 7, 8, 8, 0]]])

In [ ]:
x2

array([[9, 9, 8, 2],
       [5, 4, 5, 7],
       [9, 0, 1, 0]])

In [ ]:
x2[0,0]

9

In [ ]:
x2[0,0]=00

In [ ]:
x2

array([[0, 9, 8, 2],
       [5, 4, 5, 7],
       [9, 0, 1, 0]])

In [ ]:
x1

array([3, 9, 3, 0, 5, 6])

In [ ]:
x1[3:]

array([0, 5, 6])

In [ ]:
x1[1:4]

array([9, 3, 0])

In [ ]:
x1[::2] #begin with o and 2 is step

array([3, 3, 5])

In [ ]:
x1[::-1] #the revers array

array([6, 5, 0, 3, 9, 3])

In [ ]:
x1[4::-2]

array([5, 3, 3])

In [ ]:
x2

array([[0, 9, 8, 2],
       [5, 4, 5, 7],
       [9, 0, 1, 0]])

In [ ]:
x2[:2,:3]

array([[0, 9, 8],
       [5, 4, 5]])

In [ ]:
x2[:2,::2]

array([[0, 8],
       [5, 5]])

In [ ]:
x2[::-1,::-1]

array([[0, 1, 0, 9],
       [7, 5, 4, 5],
       [2, 8, 9, 0]])

In [ ]:
x2[:,1]

array([9, 4, 0])

In [ ]:
x2

array([[0, 9, 8, 2],
       [5, 4, 5, 7],
       [9, 0, 1, 0]])

In [ ]:
x2sub=x2[:2,:2]

In [ ]:
x2sub

array([[0, 9],
       [5, 4]])

In [ ]:
x2sub[0,0]=99

In [ ]:
x2

array([[99,  9,  8,  2],
       [ 5,  4,  5,  7],
       [ 9,  0,  1,  0]])

In [ ]:
# in numpy the slise not take a copy it takes a view

In [ ]:
graid =np.arange(1,10).reshape((3,3))

In [ ]:
graid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x=np.array([1,1,2])

In [ ]:
x.shape

(3,)

In [ ]:
x.reshape((1,3))

array([[1, 1, 2]])

In [ ]:
x.reshape((1,3)).shape

(1, 3)

In [ ]:
x.reshape((3,1)) #colum vactor

array([[1],
       [1],
       [2]])

In [ ]:
x

array([1, 1, 2])

In [ ]:
x[np.newaxis,:] #row factor

array([[1, 1, 2]])

In [ ]:
x[:,np.newaxis] #colum vector

array([[1],
       [1],
       [2]])

In [ ]:
x

array([1, 1, 2])

In [ ]:
y=np.array([3,3,3])
np.concatenate([x,y])

array([1, 1, 2, 3, 3, 3])

In [ ]:
z=np.array([9,9,9])
np.concatenate([x,y,z])

array([1, 1, 2, 3, 3, 3, 9, 9, 9])

In [ ]:
y2=np.array([[1,2,3],[4,5,6]])

In [ ]:
np.concatenate([y2,y2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
x22=rng.integers(10,size=(3,4))

In [ ]:
x22

array([[2, 2, 0, 6],
       [3, 9, 8, 3],
       [9, 0, 3, 0]])

In [ ]:
x2

array([[99,  9,  8,  2],
       [ 5,  4,  5,  7],
       [ 9,  0,  1,  0]])

In [ ]:
np.concatenate([x22,x2])

array([[ 2,  2,  0,  6],
       [ 3,  9,  8,  3],
       [ 9,  0,  3,  0],
       [99,  9,  8,  2],
       [ 5,  4,  5,  7],
       [ 9,  0,  1,  0]])

In [ ]:
np.concatenate([x22,x2],axis=0)

array([[ 2,  2,  0,  6],
       [ 3,  9,  8,  3],
       [ 9,  0,  3,  0],
       [99,  9,  8,  2],
       [ 5,  4,  5,  7],
       [ 9,  0,  1,  0]])

In [ ]:
np.concatenate([x22,x2],axis=1)

array([[ 2,  2,  0,  6, 99,  9,  8,  2],
       [ 3,  9,  8,  3,  5,  4,  5,  7],
       [ 9,  0,  3,  0,  9,  0,  1,  0]])

In [ ]:
np.vstack([x22,x2]) #equal to np.concatenate([x22,x2],axis=0)

array([[ 2,  2,  0,  6],
       [ 3,  9,  8,  3],
       [ 9,  0,  3,  0],
       [99,  9,  8,  2],
       [ 5,  4,  5,  7],
       [ 9,  0,  1,  0]])

In [ ]:
np.hstack([x22,x2]) #equal to np.concatenate([x22,x2],axis=1)

array([[ 2,  2,  0,  6, 99,  9,  8,  2],
       [ 3,  9,  8,  3,  5,  4,  5,  7],
       [ 9,  0,  3,  0,  9,  0,  1,  0]])

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
a1,a2,a3=np.split(x,[3,5])

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([4, 5])

In [ ]:
a3

array([6, 7, 8, 9])

In [ ]:
up,low=np.vsplit(graid,[2]) #will divide the array verticaly

In [ ]:
up

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
low

array([[7, 8, 9]])

In [ ]:
graid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
graid[:,0]

array([1, 4, 7])

In [ ]:
left,right=np.hsplit(graid,[2])  #will divide the array horisontaly

In [ ]:
left

array([[1, 2],
       [4, 5],
       [7, 8]])

In [ ]:
right

array([[3],
       [6],
       [9]])

In [ ]:
left[0,0]=100

In [ ]:
graid

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [ ]:
###split oparations are view not a copy

In [ ]:
def recip(values):
  output=np.empty(len(values))
  for i in range(len(values)):
    output[i]=1.0/values[i]
  return output
values=rng.integers(1,10,size=5)
values

array([8, 4, 8, 4, 1])

In [ ]:
recip(values)

array([0.125, 0.25 , 0.125, 0.25 , 1.   ])

In [ ]:
# look the time the def will take and comper with opration time
## this the difrence betwen python list and numpy array

In [ ]:
values2=rng.integers(1,100,size=100000)
%timeit recip(values2)

1.04 s ± 134 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%timeit (1.0/values2) #divide 1 on all array's elements

The slowest run took 4.38 times longer than the fastest. This could mean that an intermediate result is being cached.
393 µs ± 240 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
x=np.arange(9).reshape(3,3)

In [ ]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# you can apply opration on array without lopps
# and this kipe time

2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [ ]:
x**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
a=np.zeros(3,dtype=int)

In [ ]:
a

array([0, 0, 0])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

In [ ]:
nrg=np.random.default_rng()
l=nrg.random(100)
sum(l) #default fun. in numpy

53.33987600914234

In [ ]:
np.sum(l) #numpy fun. and the same falue of sum(l)

53.33987600914233

In [ ]:
barry=rng.random(10000)
%timeit sum(barry)

1.69 ms ± 318 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
%timeit np.sum(barry) # more time than sum(barry)

7.52 µs ± 132 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
nrg=np.random.default_rng()
x=nrg.integers(100,size=(10))

In [ ]:
x

array([15, 99, 89, 16, 99, 62, 25, 94, 34, 89])

In [ ]:
x[1]

99

In [ ]:
np.array([x[1],x[3],x[4],x[5]])

array([99, 16, 99, 62])

In [ ]:
ind=[1,2,3,4,5] #fancy indexing
x[ind]

array([99, 89, 16, 99, 62])

In [ ]:
x[[1,2,3,4,5]] # the same result of fancy

array([99, 89, 16, 99, 62])

In [ ]:
# when you indexing with array of indexes, the hape of outpot will reflect the array of indexes

In [ ]:
ind=np.array([[1,2],[3,4]])
x[ind]

array([[99, 89],
       [16, 99]])

In [ ]:
y=np.arange(12).reshape((3,4))

In [ ]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
row=np.array([0,1,2])
col=np.array([2,1,3])
y[row,col]

array([ 2,  5, 11])

In [ ]:
y[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [ ]:
row[:,np.newaxis]

array([[0],
       [1],
       [2]])

In [ ]:
y[row[:,np.newaxis],col].shape

(3, 3)